name: Daily script

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    environment: universe

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0
        
      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE }}
          token: ${{ secrets.PAT }}

      - run: rclone copy ./README.md 316:/
